from django.conf.urls import patterns, include, url
import settings
#from django.contrib import admin
from MyBlog.views import *
from MyBlog.cubeviews import  *
from MyBlog.bocaiviews import *
from MyBlog.vueviews import *
from MyBlog.adminviews import *
from MyBlog.primerviews import *
from MyBlog.helenviews import *
from MyBlog.vdreportviews import *
from MyBlog.purchaseviews import *
from MyBlog.uploadviews import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns  
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    url(r'^site_medias/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),   
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT }),
    url(r'^super/',super),
    url(r'^superlogin/',superlogin),
    url(r'^sindex/',sindex),
    url(r'^content_admin/',content_admin),
    url(r'^picture_admin/',picture_admin),
    url(r'^comment_admin/',comment_admin),
    url(r'^MyImg/delete/',deleteimgbyid),
    url(r'^MyImg/unrecycle/',unrecycleimgbyid),
    url(r'^ReplyPost/delete/',deletereplybyid),
    url(r'^ReplyPost/unrecycle/',unrecyclereplybyid),
    url(r'^user_admin/',super_admin_user),
    url(r'^delete_user/',deleteuser),
    url(r'^session_admin/',session_admin),
    url(r'^MyBlog/delete_session/',deletesessionbykey),
    url(r'^classify_admin/',classifyadmin),
    url(r'^classify_edit/(\d+)/',classifyedit),
    url(r'^MyBlog/classifyeditpost/(\d+)/',classifyeditpost),
    url(r'^MyBlog/classifyadd/',classifyadd),
    url(r'^MyBlog/classifypost/',classifypost),
    url(r'^loginout/',loginout),
    url(r'^plaza/',plaza),
    url(r'^$', index),
    url(r'^UploadImage/',UploadImage),
    url(r'^GetNewestImg',GetNewestImg),
    url(r'^MyBlog/$', index),
    url(r'^MyBlog/register/', register),
    url(r'^MyBlog/reseq/', reseq),
    url(r'^MyBlog/sregister/', sregister),
    url(r'^MyBlog/sreply/', sreply),
    url(r'^MyBlog/classfy/(\d+)/$', show_class),
    url(r'^MyBlog/ym/(\d+)/(\d+)/$', show_month),
    url(r'^MyBlog/topics/(\d+)/$',showreply),
    url(r'^MyBlog/login/',alogin),
    url(r'^MyBlog/loginout/',loginout),
    url(r'^sloginout/',sloginout),
    url(r'^reset_password/',reset_password),
    url(r'^reset_password_post/',reset_password_post),
    url(r'^MyBlog/search/',search),
    url(r'^MyBlog/oligo/',caloligo),
    url(r'^MyBlog/addseq/',addseq),
    url(r'^MyBlog/showoligo/',showoligo),
    url(r'^MyBlog/userinfo/',userinfo),
    url(r'^MyBlog/checkuser/',checkuser),
    url(r'^MyBlog/checkseq/',checkseq),
    url(r'^MyBlog/modify_userinfo/',modify_userinfo),
    url(r'^MyBlog/addblog/new/',addblog),
    url(r'^MyBlog/submitblog/',submitblog),
    url(r'^MyBlog/manageblog/$',manageblog),
    url(r'^MyBlog/myreplys/',myreply),
    url(r'^MyBlog/myphoto/',myphoto),
    url(r'^MyBlog/checklogin/',checklogin),
    url(r'^MyBlog/edit/(\d+)/',editblogbyid),
    url(r'^MyBlog/delete/',deleteblogbyid),
    url(r'^MyBlog/unrecycle/',unrecycleblogbyid),
    url(r'^MyBlog/updateblog/',updateblogbyid),
    url(r'^MyBlog/forbidden/',forbiddenuserbyid),
    url(r'^MyBlog/unforbidden/',unforbiddenuserbyid),
    url(r'^MyBlog/fedelete/',foreverdeleteuserbyid),
    url(r'^MyBlog/setsuper/',setsuperuserbyid),
    url(r'^updatephoto/',updatephotobyid),
    url(r'^MyBlog/updateblogall/',updateblogall),
#     url(r'^MyBlog/reward/',reward),
    url(r'^photo/',showphoto),
    url(r'^zanphoto/(\d+)/$',zanphoto),
    url(r'^book/',book),
    url(r'^book/tag/(\d+)',booktag),
    url(r'^movie/',movie),
    url(r'^Entrez/',Entrez),
    url(r'^downloadentrez/',downloadEntrez),
    url(r'^MyBlog/',static),
    url(r'^upload/', UploadImage),
    url(r'^img_upload/', upload),
    url(r'^fujian_add/', fujian_add),
    url(r'^show', showImg),
    url(r'^testimg/', TestImg),
    url(r'^cube/', cube),
    url(r'^cube_3x3/', cube33),
    url(r'^cube_4x4/', cube44),
    url(r'^cube_pyraminx/', cube_pyraminx),
    url(r'^bocai/', bocai),
    url(r'^kaipan/', kaipan),
    url(r'^html2ubb/', html2ubb),
    url(r'^score2ubb/', score2ubb),
    url(r'^dagaier/', dagaier),
    url(r'^getimage/', getimage),
    url(r'^yyjp/', yyjp),
    url(r'^getyyjp/', getyyjp),
    url(r'^checkAccessionLen/(.+)/$',checkAccessionLen),
    url(r'^primer/',primerdesigner),
    url(r'^seqview/',seqview),
    url(r'^basemodify/',basemodify),
    url(r'^seqinput/',seqinput),
    url(r'^seqread/',seqread),
    url(r'^pcr-principle/',pcrprincp),
    url(r'^primer-manual/',manual),
    url(r'^multipcr/',multiprimer),
    url(r'^multiseqview/',multiseqview),
    url(r'^helen/',helen),
    url(r'^clin_table_2x2/',clin_table),
    #VD report system
    url(r'^vdreport/',vdreport),
    url(r'^vdlogin/',vdlogin),
    url(r'^vdloginout/',vdloginout),
    url(r'^vdindex/',vdindex),
    url(r'^applicant_admin/',applicant_admin),
    url(r'^applicantpost/',applicantpost),
    url(r'^applicant_list/',applicant_list),
    url(r'^applicant_result_admin/(\d+)/$',applicant_result_admin),
    url(r'^applicantresultpost/(\d+)/$',applicantresultpost),
    url(r'^applicant_result_list/',applicant_result_list),
    url(r'^applicant_prescription_admin/(\d+)/(\d+)/$',applicant_presciption_admin),
    url(r'^applicantprescriptionpost/(\d+)/(\d+)/$',applicantprescriptionpost),
    url(r'^applicant_result_print/',applicant_result_print),
    url(r'^applicant_print_admin/(\d+)/$',applicant_print_admin),
    url(r'^applicant_printed_admin/(\d+)/$',applicant_printed_admin),
    url(r'^applicant_report_is_printable/(\d+)/$',applicant_report_is_printable),
    url(r'^applicant_print_query/',applicant_print_query),
    #purchase admin system
    url(r'^purchaseadmin/',purchaseadmin),
    url(r'^palogin/',palogin),
    url(r'^paloginout/',paloginout),
    url(r'^paindex/',paindex),
    url(r'^material_admin/',material_admin),
    url(r'^contact_admin/',contact_admin),
    url(r'^contactpost/',contactpost),
    url(r'^materialpost/',materialpost),
    url(r'^material_list/',material_list),
    url(r'^material_contact/$',material_contact_add),
    url(r'^material_contact_list/$',material_contact_list),
    url(r'material_contact_quotation/(\d+)/$',material_contact_quotation),
    url(r'materialcontactquotationpost/(\d+)/$',materialcontactquotationpost),
    url(r'material_contact_query/',material_contact_query),
    url(r'material_query/',material_query),
    url(r'material_query_all/',material_query_all)
)
